# Generated by Django 5.2.1 on 2025-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
