# Generated by Django 5.2.1 on 2025-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
