# Generated by Django 5.2.1 on 2025-05-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='date',
            new_name='created_at',
        ),
    ]
